<?xml version="1.0"?>
<robot name = "robot" xmlns:xacro="https://www.ros.org/wiki/xacro">

<xacro:property name="yaml_file" value="$(find diff_drive)/config/physical.yaml"/>
<xacro:property name="params" value="${xacro.load_yaml(yaml_file)}"/>
<xacro:property name="base_size" value="${params['/**']['ros__parameters']['base_size']}"/>
<xacro:property name="width" value="${params['/**']['ros__parameters']['width']}"/>
<xacro:property name="length" value="${params['/**']['ros__parameters']['length']}"/>
<xacro:property name="wheel_r" value="${params['/**']['ros__parameters']['wheel_r']}"/>
<xacro:property name="wheel_l" value="${params['/**']['ros__parameters']['wheel_l']}"/>
<xacro:property name="caster_r" value="${params['/**']['ros__parameters']['caster_r']}"/>

<xacro:arg name="gazebo" default="false"/>
    <xacro:if value="$(arg gazebo)">
        <xacro:include filename="$(find diff_drive)/urdf/ddrive.gazebo.xacro" />
    </xacro:if>

<link name="base_link">
    <visual>
        <geometry>
            <box size="${length} ${base_size} ${width}"/>
        </geometry>
        <material name="blue_mat">
            <color rgba="0 0 1 1"/>
        </material>
    </visual>
    <collision>
        <geometry>
            <box size="${length} ${base_size} ${width}"/>
        </geometry>
    </collision>
    <inertial>
      <mass value='5'/>
      <!-- should be using formulas for the inertia based on the parameters-->
        <inertia ixx='0.02' ixy='0' ixz='0' iyy='0.15' iyz='0' izz='0.16'/>
    </inertial> 
</link>

<link name = "left_wheel">
    <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/> 
        <geometry>
            <cylinder radius="${wheel_r}" length="${wheel_l}"/>
        </geometry>
        <material name='red_mat'>
            <color rgba = "1 0 0 0.8"/>
        </material>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_r}" length="${wheel_l}"/>
        </geometry>
    </collision>
    <inertial>
        <mass value='3'/>
        <inertia ixx='0.011' ixy='0' ixz='0' iyy='0.02' iyz='0' izz='0.01'/>
    </inertial> 
</link>

<link name = "right_wheel">
    <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_r}" length="${wheel_l}"/>
        </geometry>
        <material name='red_mat'>
            <color rgba = "1 0 0 0.8"/>
        </material>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_r}" length="${wheel_l}"/>
        </geometry>
    </collision>
    <inertial>
        <mass value='3'/>
        <inertia ixx='0.011' ixy='0' ixz='0' iyy='0.02' iyz='0' izz='0.01'/>
    </inertial> 
</link>

<link name="top_caster">
    <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <sphere radius="${caster_r}"/>
        </geometry>
        <material name='green_mat'>
            <color rgba = "0 1 0 1"/>
        </material>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <sphere radius="${caster_r}"/>
        </geometry>
    </collision>
    <inertial>
        <mass value='0.2'/>
        <inertia ixx='0.000128' ixy='0' ixz='0' iyy='0.000128' iyz='0' izz='0.000128'/>
    </inertial> 
</link>

<link name="bottom_caster">
    <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <sphere radius="${caster_r}"/>
        </geometry>
        <material name='green_mat'>
            <color rgba = "0 1 0 1"/>
        </material>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <sphere radius="${caster_r}"/>
        </geometry>
    </collision>
    <inertial>
        <mass value='0.2'/>
        <inertia ixx='0.000128' ixy='0' ixz='0' iyy='0.000128' iyz='0' izz='0.000128'/>
    </inertial> 
</link>

<joint name="base_l_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="${length/2} ${base_size/2+wheel_l} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
</joint>

<joint name="base_r_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="${length/2} -${base_size/2+wheel_l} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
</joint>

<joint name="base_top_caster_joint" type="continuous">
  <parent link="base_link"/>
  <child link="top_caster"/>
  <origin xyz="-${length/2 - 2*caster_r} 0 ${width/2 + caster_r}" rpy="0 0 0"/>
  <axis xyz="0 1 0"/>
</joint>

<joint name="base_bottom_caster_joint" type="continuous">
  <parent link="base_link"/>
  <child link="bottom_caster"/>
  <origin xyz="-${length/2 - 2*caster_r} 0 -${width/2 + caster_r}" rpy="0 0 0"/>
  <axis xyz="0 1 0"/>
</joint>
</robot>
